server {
    server_name admin.newbeecard.com;
    listen 443 ssl;
    include conf.d/options-ssl-nbc-admin.conf;

    # 静态文件目录
    root /nbc/admin;
    client_max_body_size 50M;

    # 静态文件索引
    index index.html index.htm;
    # 配置静态文件访问
    location / {
        try_files $uri $uri/ =404;
    }

    # 配置代理到后端服务
    location /api/ {
       if ($http_user_agent = Mozilla/4.0){
        	return 503;
         }
	    proxy_set_header X-Real-IP $remote_addr;
     	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
 	    proxy_set_header X-NginX-Proxy true;
	    rewrite ^/api(/.*)$ $1 break;
	    proxy_redirect off;
	    proxy_pass http://nbc_backend;
    }
}
server {
    listen 80;
    server_name admin.newbeecard.com;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 其他所有请求暂时重定向到 HTTPS（首次申请时，可以先注释掉这行）
    location / {
        return 301 https://$host$request_uri;
    }
}
